import type { Blueprint, Competitor, Startup, StartupAssessment, StartupProfile } from "../types";

export interface ExportBundle {
  startup: Startup;
  profile: StartupProfile;
  blueprint: Blueprint | null;
  assessment: StartupAssessment | null;
}

export function blueprintToMarkdown(bundle: ExportBundle): string {
  const header = [
    `# ${bundle.startup.name}`,
    `> ${bundle.startup.tagline}`,
    "",
    `_Generated by ForgeAI · ${new Date().toLocaleDateString()}_`,
    "",
    `**Stage:** ${bundle.startup.stage}  `,
    bundle.assessment ? `**Startup score:** ${bundle.assessment.score.total}/100 (${bundle.assessment.score.grade})` : "",
    "",
  ].filter(Boolean).join("\n");

  const sections = (bundle.blueprint?.sections ?? [])
    .map((s) => `## ${s.title}\n\n${s.content.trim()}\n`)
    .join("\n---\n\n");

  return `${header}\n---\n\n${sections}`.trim() + "\n";
}

export function roadmapToCsv(rows: { phase: string; title: string; status: string; priority: string; dueDate?: string }[]): string {
  const esc = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const lines = ["Phase,Task,Status,Priority,Due date"];
  for (const r of rows) lines.push([r.phase, r.title, r.status, r.priority, r.dueDate ?? ""].map(esc).join(","));
  return lines.join("\n");
}

export function competitorsToCsv(rows: Competitor[]): string {
  const esc = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const lines = ["Company,Product,Target users,Pricing,Strengths,Weaknesses,Differentiation,Verified"];
  for (const c of rows)
    lines.push(
      [c.company, c.product, c.targetUsers, c.pricing, c.strengths.join("; "), c.weaknesses.join("; "), c.differentiation, c.verified ? "yes" : "no"]
        .map(esc)
        .join(",")
    );
  return lines.join("\n");
}

export function startupToJson(bundle: ExportBundle): string {
  return JSON.stringify(bundle, null, 2);
}

export function fileSlug(startupName: string, kind: string): string {
  const safe = startupName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "startup";
  return `forgeai-${safe}-${kind}`;
}