"use client";

import { useState } from "react";
import type { StartupContext } from "@/lib/startup";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { useToast } from "@/components/ui/toast";
import { Sparkles, RefreshCw, Pencil, Check, TrendingUp, Swords, Users, Store, Package, Rocket, Cpu, Map, Megaphone, Send } from "lucide-react";

const ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  TrendingUp,
  Swords,
  Users,
  Store,
  Package,
  Rocket,
  Cpu,
  Map,
  Megaphone,
  Send,
};
import Link from "next/link";
import { fetcher } from "@/lib/utils";

export function renderValue(value: unknown, depth = 0): React.ReactNode {
  if (value === null || typeof value === "undefined") {
    return <span className="text-xs text-[var(--fg-muted)]">—</span>;
  }
  if (typeof value === "string") {
    if (value === "") return <span className="text-xs text-[var(--fg-muted)]">—</span>;
    return <span className="text-sm leading-relaxed text-[var(--fg-secondary)]">{value}</span>;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return <span className="text-sm text-[var(--fg-secondary)]">{String(value)}</span>;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return <span className="text-xs text-[var(--fg-muted)]">None listed</span>;
    }
    if (value.every((v) => typeof v === "string")) {
      return (
        <div className="flex flex-wrap gap-1.5">
          {(value as string[]).map((v, i) => (
            <Badge key={i} tone="default">{v}</Badge>
          ))}
        </div>
      );
    }
    return (
      <div className="space-y-3">
        {(value as unknown[]).map((item, i) => (
          <Card key={i} className="bg-[var(--elevated)]">
            <CardBody className="px-4 py-3">
              {typeof item === "object" && item !== null ? (
                <ObjectFields value={item as Record<string, unknown>} />
              ) : (
                renderValue(item, depth + 1)
              )}
            </CardBody>
          </Card>
        ))}
      </div>
    );
  }
  if (typeof value === "object") {
    return <ObjectFields value={value as Record<string, unknown>} />;
  }
  return <span className="text-sm text-[var(--fg-secondary)]">{String(value)}</span>;
}

export function ObjectFields({ value }: { value: Record<string, unknown> }) {
  const entries = Object.entries(value);
  if (entries.length === 0) return null;
  return (
    <div className="grid gap-4 md:grid-cols-2">
      {entries.map(([k, v]) => {
        return (
          <div key={k} className="rounded-lg border border-[var(--border-soft)] bg-[var(--surface)] p-3.5">
            <p className="text-[11px] font-medium uppercase tracking-wider text-[var(--fg-muted)]">
              {k.replace(/([A-Z])/g, " $1")}
            </p>
            <div className="mt-2">{renderValue(v, 1)}</div>
          </div>
        );
      })}
    </div>
  );
}

export interface SectionWorkspaceProps {
  ctx: StartupContext;
  sectionKey: string;
  title: string;
  icon: string;
  description: string;
  emptyState: { title: string; description: string };
  schemaHint?: string;
}

export function SectionWorkspace({
  ctx,
  sectionKey,
  title,
  icon,
  description,
  emptyState,
}: SectionWorkspaceProps) {
  const { toast } = useToast();
  const Icon = ICONS[icon] ?? Sparkles;
  const startup = ctx.startup!;
  const [data, setData] = useState<unknown>(ctx.sections[sectionKey] ?? null);
  const [regenerating, setRegenerating] = useState(false);
  const [editing, setEditing] = useState(false);
  const [editValue, setEditValue] = useState("");

  async function regenerate() {
    setRegenerating(true);
    try {
      const res = await fetcher<{ ok: boolean; data: unknown }>("/api/generate", {
        method: "POST",
        body: JSON.stringify({ action: "regenerate", startupId: startup.id, section: sectionKey }),
      });
      setData(res.data);
      toast("Section regenerated by Zorvyn", "success");
    } catch (err) {
      toast(err instanceof Error ? err.message : "Regeneration failed", "error");
    } finally {
      setRegenerating(false);
    }
  }

  function startEdit() {
    setEditValue(JSON.stringify(data ?? {}, null, 2));
    setEditing(true);
  }

  function saveEdit() {
    try {
      const parsed = JSON.parse(editValue);
      setData(parsed);
      setEditing(false);
      toast("Saved", "success");
    } catch {
      toast("Invalid JSON", "error");
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div className="flex size-10 items-center justify-center rounded-xl border border-[var(--border-soft)] bg-[var(--elevated)]">
            <Icon className="size-5 text-[var(--accent)]" />
          </div>
          <div>
            <h1 className="text-xl font-semibold tracking-tight text-[var(--fg)]">{title}</h1>
            <p className="mt-1 max-w-md text-sm text-[var(--fg-muted)]">{description}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {data ? (
            <>
              {editing ? (
                <Button size="sm" onClick={saveEdit}>
                  <Check className="size-3.5" /> Save
                </Button>
              ) : (
                <Button size="sm" variant="ghost" onClick={startEdit}>
                  <Pencil className="size-3.5" /> Edit
                </Button>
              )}
              <Button size="sm" variant="ghost" onClick={regenerate} loading={regenerating}>
                <RefreshCw className="size-3.5" /> Regenerate
              </Button>
            </>
          ) : null}
        </div>
      </div>

      {!data ? (
        <>
          <EmptyState
            icon={<Icon className="size-5" />}
            title={emptyState.title}
            description={emptyState.description}
            action={
              <Button size="sm" onClick={regenerate} loading={regenerating}>
                <Sparkles className="size-3.5" /> Generate with Zorvyn AI
              </Button>
            }
          />
          <p className="text-xs text-[var(--fg-muted)]">
            <Link href="/cofounder" className="text-[var(--accent)] hover:underline">
              Prefer to discuss first?
            </Link>{" "}
            Ask Zorvyn to draft this section in the AI workspace.
          </p>
        </>
      ) : (
        <Card>
          <CardHeader
            title={title}
            action={
              <Badge tone="accent">
                <Sparkles className="size-3" /> Zorvyn AI
              </Badge>
            }
          />
          <CardBody>
            {editing ? (
              <textarea
                className="min-h-64 w-full rounded-lg border border-[var(--border)] bg-[var(--elevated)] p-3 font-mono text-xs text-[var(--fg)] focus:border-[var(--accent)] focus:outline-none"
                value={editValue}
                onChange={(e) => setEditValue(e.target.value)}
                spellCheck={false}
              />
            ) : (
              renderValue(data)
            )}
          </CardBody>
        </Card>
      )}
    </div>
  );
}